version: '3'

services:
  backend:
    build: ./backend
    command: npm run start:migrate:prod
    restart: unless-stopped
    environment:
      - PORT=4000
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    volumes:
      - ./sharedUtils:/sharedUtils
#  frontend:
#    build: ./frontend
#    command: npm run prod
#    restart: unless-stopped
#    ports:
#      - "3000:3000"
#    volumes:
#      - ./sharedUtils:/sharedUtils
  postgres:
    image: postgres:15.1-alpine
    environment:
      POSTGRES_USER: "castlewars"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "castlewars"
    ports:
      - "5432:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data
