version: '3'

services:
  backend:
    build: ./backend
    restart: unless-stopped
    environment:
      - PORT=4000
    ports:
      - "4000:4000"
    depends_on:
      - postgres
      - shared_utils
    volumes:
      - ./sharedUtils:/sharedUtils
  frontend:
    build: ./frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - shared_utils
    volumes:
      - ./sharedUtils:/sharedUtils
  shared_utils:
    build: ./sharedUtils
    volumes:
      - ./sharedUtils:/app
  postgres:
    image: postgres:15.1-alpine
    environment:
      POSTGRES_USER: "castlewars"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "castlewars"
    ports:
      - "5432:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data
