version: '3'

services:
#  api:
#    build: .
#    command: npm run start
#    restart: unless-stopped
#    environment:
#      - PORT=4000
#    ports:
#      - "4000:4000"
  postgres:
    image: postgres:15.1-alpine
    environment:
      POSTGRES_USER: "castlewars"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "castlewars"
    ports:
      - "5432:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data
#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 8080:8080


